src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $firstname = null;

    #[ORM\Column(length: 100)]
    private ?string $lastname = null;

    #[ORM\Column(length: 20)]
    private ?string $gender = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $deletedAt = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    public function getFullname():string
    {
        return $this->getFirstname() . '' . $this->getLastname();
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\Produit;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{


    #[Route('/', name: 'default_home', methods: ['GET'])]
    public function home(EntityManagerInterface $entityManager): Response
    {
        $produits = $entityManager->getRepository(Produit::class)->findBy(['deletedAt' => null]);

        return $this->render('default/home.html.twig', [
            'produits' => $produits
        ]);
    }

    #[Route('/profile/voir-mes-infos', name: 'show_profile', methods: ['GET'])]
    public function showProfile(EntityManagerInterface $entityManager): Response
    {
        $commands = $entityManager->getRepository(Commande::class)->findBy(['deletedAt' => null]);

        return $this->render('default/show_profile.html.twig', [
            'commands' => $commands
        ]);
    }



}

templates/default/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

    {% include 'include/_flashes.html.twig' %}

    <h1 class="text-center my-4">Bienvenue sur la boutique en ligne</h1>

    <div class="row mb-3 d-flex justify-content-around">

        {%  for produit in produits %}

            <div class="col-3 mx-2">
                <div class="card" style="width: 18rem;">
                    <img src="{{ asset('uploads/' ~ produit.photo) }}" class="card-img-top" alt="une photo" style="object-fit: contain;" width="150" height="220">
                    <div class="card-body">
                        <h5 class="card-title">{{ produit.title }}</h5>
                        <p class="card-text">{{ produit.description | length > 50 ? produit.description | slice(0,50) ~ '...' : produit.description }}</p>
                        <a href="{{ path('add_item', {'id': produit.id}) }}" class="col-12 btn btn-warning text-center"><i class="fa-solid fa-cart-plus"></i></a>
                    </div>
                </div>
            </div>

        {% else %}
            <h3 class="text-center">Aucun article en ligne</h3>
        {% endfor %}

    </div>

{% endblock %}

templates/default/show_profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte
{% endblock %}

{% block body %}

	<h1 class="text-center my-3">Vos informations</h1>

	<div class="row">
		<div class="col-10 mx-auto">
			{% include 'include/_flashes.html.twig' %}
		</div>
	</div>

	<div class="row">
		<div class="col-8 mx-auto">

			<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
				<li class="nav-item" role="presentation">
					<button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Voir mon compte</button>
				</li>
				<li class="nav-item" role="presentation">
					<button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Mes commandes</button>
				</li>
			</ul>
			<div class="tab-content" id="pills-tabContent">
				<div class="tab-pane fade show active mb-3" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

					<div class="card text-center">
						<div class="card-header bg-warning">
							Mes informations de compte
						</div>
						<div class="card-body">
							<h5 class="card-title">{{ app.user.firstname }}
								{{ app.user.lastname }}</h5>
							<p class="card-text">Email :
								{{ app.user.email }}</p>
							<p class="card-text">Rôle:
								{{ app.user.roles is same as 'ROLE_ADMIN' ? 'Administrateur' : 'Membre' }}</p>
							<div class="row">
								<div class="col-6">
									<a href="#" class="btn btn-warning text-white">Modifier mes informations</a>
								</div>
								<div class="col-6">
									<a href="#" class="btn btn-warning text-danger">Changer mon mot de passe</a>
								</div>
							</div>
						</div>
					</div>

				</div>
				{# end .pills-home-tab #}

				{# ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #}

				<div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">

					<div class="row">
						<div class="col">

							<table class="table">

								<thead class="table-dark">
									<tr>
										<th>Commande N°#</th>
										{#                                    <th>Membre</th>#}
										<th>Quantité</th>
										<th>Montant</th>
										<th>État</th>
										<th>Passée le</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>

									{% for  command in commands %}

										<tr>
											<td>{{ command.id }}</td>
											{#                                        <td>{{ command.user.id }} - {{ command.user.fullname }} - {{ command.user.email }}</td>#}
											{# <td>{{ produit.id }} - {{ produit.title }}</td>#}
											<td>{{ command.quantity }}</td>
											<td>{{ command.total }}</td>
											<td>{{ command.status }}</td>
											<td>{{ command.createdAt | date('d/m/Y') }}
												-
												{{ command.createdAt | date('H:i') }}</td>
											<td>
												<a href="" title="Annuler la commande" class="btn btn-sm btn-danger">
													<i class="fa-solid fa-times"></i>
												</a>
											</td>
										</tr>
									{% else %}
										<tr>
											<td colspan="8" class="text-center bg-warning">Aucune commande en cours</td>
										</tr>
									{% endfor %}

								</tbody>
							</table>

						</div>
					</div>

				</div>
				{# end .pills-profile-tab #}

				{# ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #}

			</div>

		</div>
		{# end .col-8 #}
	</div>
	{# end .row #}

{% endblock %}